use ginmi::Client;

const CERT: &str = "-----BEGIN CERTIFICATE-----
MIIDyDCCArCgAwIBAgICBnowDQYJKoZIhvcNAQELBQAwUTELMAkGA1UEBhMCVVMx
CTAHBgNVBAcTADEVMBMGA1UEChMMY29udGFpbmVybGFiMQkwBwYDVQQLEwAxFTAT
BgNVBAMTDHNybDAxIGxhYiBDQTAeFw0yNDAyMTMwOTU1NDZaFw0yNTAyMTMwOTU1
NDZaMFExCzAJBgNVBAYTAlVTMQkwBwYDVQQHEwAxFTATBgNVBAoTDGNvbnRhaW5l
cmxhYjEJMAcGA1UECxMAMRUwEwYDVQQDEwxzcmwuc3JsMDEuaW8wggEiMA0GCSqG
SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDYx4YWzDD+/IOmJ2ym2Kg2HKlJiDYkL6Xv
3mkut7C5458K901CbZISkSR5d736CSNzOVrpYq72XNzLVdRrM1bgcSEtIL4srrvQ
NVdLjCooqqm7a7IZPOHyF01OHOZ9MwrPcYfzl7UdPqmwE/518aNki6jLZn0S+p5T
1mC7V/MTWBsyvSNuMXYv31dvCM4FOWwrrL4vm5BC+Ru2Bdk9P8eISfnorwW57EvD
F38psWQMjVb63PY7Lih5fke1CfUvAVUph0yjhSalpOUfmuRt2n9SS5w/O8XSnuyi
bJTjTz6lTwWxb4JQq3FTzDFUkqRVG+KE/GA9c6osP0KI0w4mkDtbAgMBAAGjgakw
gaYwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcD
ATAOBgNVHQ4EBwQFAQIDBAYwHwYDVR0jBBgwFoAUosVhzOrk9vuT3YhrHHWjehVM
wS0wRAYDVR0RBD0wO4IDc3Jsgg5jbGFiLXNybDAxLXNybIIMc3JsLnNybDAxLmlv
hwSsFBQChxAgAQFyACAAIAAAAAAAAAACMA0GCSqGSIb3DQEBCwUAA4IBAQDYd5Z8
QAgQod+xB7LKWpu2cq/9paZyVCIdBt3VNfWhulNPtFRwB2uvy/d1VQ1OtIhW81m5
pLfmO++wT9n513ZNlf74NRLgz9ICQj5cVL7upmCsNf0WwfuND6Ok9GfqAqJ9MYtz
aEQ2gOfI/oTDUNhbu7wzv/742bJamYO7/JSc/h9pKkK0mWSBSol+6uin/XYUBmoR
s5MiNiP1jf/p9nsilMzxvlqcvlNzmdhk0/+e1sVrfHgJT97L5EAm2knOqy6eYsGj
z7PLzMcAwnX+x8bDRXaEZQvrMlZLIK7VEYpMYF0JO2FV0eC9BCDnfYQ+ENfKPTuU
DTJWp31iboNSSGVv
-----END CERTIFICATE-----";

#[tokio::test]
async fn test_client_connect() {
    let mut client = Client::builder("https://clab-srl01-srl:57400")
        .tls(CERT, "clab-srl01-srl")
        .build()
        .await
        .unwrap();

    let capabilities = client.capabilities().await;
    assert_eq!("0.10.0", capabilities.g_nmi_version);
}